name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate artifacts
        run: yarn generate
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: thoughts
          folder: .output/public
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
